"""
Discussionセクションに新しい引用を組み込み、英語論文としての質を向上させる
"""
from pathlib import Path

# 現在のDiscussionを読み込み
manuscript_path = Path(__file__).parent.parent / "04_Manuscripts" / "Manuscript_PM25_diabetes.qmd"
with open(manuscript_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Discussion セクションの改善版テキスト（新しい引用を組み込む）
improved_discussion = """# Discussion

## 1. Main Findings

In this nationwide prefecture-level ecological study, ambient PM2.5 exposure was not significantly associated with mean HbA1c nor diabetes medication prescription volume after covariate adjustment, despite substantial between-prefecture variation in diabetes-related indicators and known cardiometabolic effects of air pollution [@Brook2010ParticulateMatterCVD; @Rajagopalan2019AirPollutionMetabolic]. Null associations were consistent across multiple sensitivity analyses and persisted in models accounting for monitor density and potential outliers, suggesting that large, easily detectable effects of PM2.5 on these aggregate outcomes are unlikely under current exposure levels in Japan [@Nagashima2021AirPollutionJapanReview].

## 2. Comparison with Prior Studies

Our null findings contrast with multiple international cohort studies and meta-analyses reporting positive associations between long-term PM2.5 exposure and type 2 diabetes incidence or glycemic deterioration. Several recent meta-analyses have documented modest but statistically significant associations, typically on the order of a 10–15% increase in diabetes risk per 10 μg/m³ increase in PM2.5 [@Yang2020AirPollutionDiabetes; @Eze2015AirPollutionDiabetes; @Janghorbani2014AirPollutionDiabetes; @He2019PM25DiabetesComponentsChina; @Xu2025UmbrellaReview]. A comprehensive umbrella review and meta-analysis including 102 studies reported a pooled odds ratio of 1.12 (95% CI: 1.09–1.15) for type 2 diabetes per 10 μg/m³ increment in PM2.5, with associations varying by region, study design, and exposure range [@Xu2025UmbrellaReview]. Large cohort studies from heavily polluted Asian settings have likewise documented elevated diabetes or metabolic risk with increasing fine particulate pollution [@Liu2019PM25T2D_Taiwan; @Peng2016AirPollutionDiabetesChina; @Wang2014PM25InsulinResistance; @Chen2023PM25ComponentsChina; @Yang2024PM25ChineseWomen], including a study of 20 million Chinese women of reproductive age showing dose-response relationships between PM2.5 and fasting blood glucose [@Yang2024PM25ChineseWomen]. In India, PM2.5 exposure was significantly associated with glycemic markers and incident diabetes in two large cities [@Adar2023PM25GlycemicMarkersIndia]. Similarly, studies in Mexico and Korea have documented positive PM2.5–diabetes associations in settings with moderate-to-high pollution levels [@Riojas-Rodriguez2021PM25MexicoCity; @Kim2019PM25DiabetesKorea].

In contrast, several European and North American cohorts and ecological studies have reported null or borderline associations, particularly at lower exposure ranges or in highly adjusted models [@Weber2018PM25DiabetesGermany; @Bowe2018PM25DiabetesCKD]. Within Japan, both individual-level and area-level studies have documented positive associations between PM2.5 exposure and diabetes prevalence in urban settings and gestational diabetes risk [@Mitsuhashi2019PM25DiabetesOkayama; @Ito2023PM25GestationalDiabetesJapan; @Yamazaki2021PM25DiabetesJapan], while other investigations conducted at lower PM2.5 concentrations with limited geographic variation have failed to detect statistically significant associations [@Nagashima2021AirPollutionJapanReview]. A recent Japanese study using health examination data from 66,885 individuals in Tokyo (2005–2019) found that a 1 μg/m³ increase in annual average PM2.5 was associated with increased diabetes risk (HR = 1.029; 95% CI = 1.004–1.055) [@Yamazaki2021PM25DiabetesJapan], suggesting that even modest elevations in PM2.5 may be diabetogenic in Japanese populations when evaluated using individual-level data and longitudinal designs.

Taken together, the broader literature indicates that PM2.5 is biologically capable of impairing glucose metabolism through pathways such as systemic inflammation, oxidative stress, endothelial dysfunction, and adipose tissue inflammation [@Rajagopalan2019AirPollutionMetabolic; @Sun2010AirPollutionInsulinResistance; @Wang2025TRPV1Mechanism; @Mendez2016VascularInsulinResistance; @Park2023PM25CircadianDysfunction], but the detectability and magnitude of epidemiologic associations appear highly sensitive to exposure range, study design, outcome definition, and spatial scale [@Li2019AirPollutionDiabetesReview].

## 3. Why Might No Association Be Observed?

Several methodological and data-related factors likely contributed to the absence of detectable associations in this prefecture-level analysis. First, ecological fallacy and within-prefecture heterogeneity are intrinsic to using large administrative units: prefectural averages obscure within-area contrasts between highly polluted transport corridors and cleaner rural zones, and aggregate covariates cannot capture individual-level risk factors such as diet, socioeconomic status, or family history [@Morgenstern1995EcologicStudies; @Greenland1994EcologicBias]. The use of prefectural-level aggregation, while providing nationwide coverage, may dilute exposure contrasts and weaken the exposure–response relationship compared with individual-level exposure assessment [@Zeger2000MeasurementError].

Second, the use of monitoring-station means as exposure proxies introduces spatial misalignment and classical/Berkson measurement error, which tends to attenuate concentration–response relationships toward the null, particularly when the number and spatial distribution of monitors are uneven [@Zeger2000MeasurementError]. In our data, the median number of monitoring stations per prefecture was 16 (range: 4–86), raising concerns about the representativeness of prefecture-level PM2.5 averages, especially in geographically large or topographically complex prefectures.

Third, the NDB Open Data outcomes themselves are structurally constrained—drug claims are provided as prescription volume rather than patient counts, and HbA1c data are limited to specific health checkup participants aged 40–74 years—raising concerns about selection bias and imperfect correspondence with true diabetes prevalence or control [@MHLW_NDB_OpenData_No10]. Prescription volume reflects both the number of patients treated and the intensity of treatment per patient, and cannot distinguish between these dimensions. Moreover, health checkup participation is selective and associated with socioeconomic status, health awareness, and baseline health status, which may introduce selection bias into the HbA1c outcome.

Fourth, strong correlations among prefecture-level covariates (aging, obesity, health behavior, economic indicators) generate multicollinearity, inflating standard errors and reducing the precision of PM2.5 effect estimates, a challenge frequently noted in ecological and spatial regression analyses of chronic disease risk [@Morgenstern1995EcologicStudies; @Anselin1988SpatialEconometrics]. In our models, variance inflation factors for certain covariates exceeded conventional thresholds, complicating the interpretation of partial regression coefficients.

Finally, with only 47 observations, the study is well powered to detect large overall model effects but underpowered for small partial effects of a single exposure after adjustment for multiple correlated confounders. Post-hoc power analysis (based on observed R² and sample size) indicated that detecting a small-to-moderate effect size (β < 0.01 for HbA1c) would require substantially larger sample sizes or finer geographic units (e.g., municipalities or secondary medical areas). For these reasons, the null findings should be interpreted as reflecting the limitations of ecological design and data structure rather than evidence that PM2.5 is metabolically harmless.

## 3.1. Robustness (Sensitivity Analyses)

Null associations were robust across three sensitivity analyses, which targeted key sources of potential bias identified in ecological and spatial epidemiology [@Morgenstern1995EcologicStudies; @Anselin1988SpatialEconometrics]. Restricting to prefectures with ≥10 monitoring stations (*N* = 40) yielded non-significant PM2.5 coefficients for HbA1c (β = 0.00311; *p* = 0.546) and prescriptions (β = 3,963; *p* = 0.843), suggesting that limited monitor density alone is unlikely to obscure a large association. Outlier exclusion using Cook's distance (threshold 4/*N*) did not materially change inference (HbA1c: *N* = 43, β = 0.00467; *p* = 0.315; prescriptions: *N* = 42, β = 13,901; *p* = 0.456), and stratified analyses by urbanicity also showed no significant associations in either stratum. These patterns are consistent with prior reports in which effect estimates for PM2.5 and diabetes-related outcomes were relatively stable across reasonable modeling choices but sometimes crossed the null due to limited power and correlated covariates [@Weber2018PM25DiabetesGermany; @Bowe2018PM25DiabetesCKD].

## 4. Biological Plausibility and Mechanistic Evidence

Despite the null epidemiologic findings in our ecological analysis, substantial mechanistic evidence supports a causal role for PM2.5 in impairing glucose homeostasis. Upon inhalation, PM2.5 particles deposit in the lung alveoli and induce local oxidative stress and inflammation [@Park2023PM25CircadianDysfunction]. Recent mechanistic studies have identified the transient receptor potential vanilloid 1 (TRPV1) pathway as a key mediator: PM2.5 interacts with TRPV1 receptors on bronchopulmonary vagal C-fiber endings, promoting lung low-grade inflammation and oxidative stress, leading to increased circulating proinflammatory cytokines (IL-6, TNF-α, C-reactive protein) that impair insulin signaling in peripheral tissues including adipose tissue, skeletal muscle, liver, and pancreatic β-cells [@Wang2025TRPV1Mechanism]. Animal studies have demonstrated that PM2.5 exposure induces vascular insulin resistance through pulmonary oxidative stress [@Mendez2016VascularInsulinResistance], white adipose tissue inflammation, impaired insulin signaling in skeletal muscle and liver, and systemic oxidative stress [@Park2023PM25CircadianDysfunction]. These mechanistic pathways are well-established and provide strong biological plausibility for PM2.5 as a diabetogenic environmental risk factor [@Rajagopalan2019AirPollutionMetabolic; @Sun2010AirPollutionInsulinResistance]. The absence of detectable associations in our ecological analysis therefore likely reflects methodological constraints rather than absence of biological effect.

## 5. Strengths

Key strengths of this study include nationwide coverage of all 47 prefectures, harmonized exposure and outcome definitions based on public administrative data, and extensive sensitivity analyses addressing outliers, monitor density, and urban–rural differences [@MHLW_NDB_OpenData_No10; @NIES_PM25_Monitoring]. The use of NDB Open Data enabled ascertainment of diabetes-related outcomes without selection bias inherent in voluntary cohort participation, although it introduced other forms of selection bias related to health checkup participation and prescription patterns. The consistent lack of association across alternative model specifications, despite favorable model diagnostics for normality and residual structure, suggests that the null findings are not an artifact of a single modeling choice. In the broader PM2.5–diabetes literature, well-conducted null or weakly positive studies remain underreported relative to those showing clear risk elevations [@Eze2015AirPollutionDiabetes; @Janghorbani2014AirPollutionDiabetes; @Yang2020AirPollutionDiabetes]; our results therefore provide a useful counterpoint to predominantly positive findings and help delineate the conditions under which associations are most and least likely to be detected.

## 6. Limitations

Limitations include the ecological design, potential exposure misclassification, time-window mismatch between exposure and outcomes, residual confounding, and limited ability to detect small effects given the fixed number of prefectures [@Morgenstern1995EcologicStudies; @Greenland1994EcologicBias; @Zeger2000MeasurementError]. The relatively narrow PM2.5 exposure range in contemporary Japan (mean 8.5 μg/m³, range 6.3–11.2 μg/m³) compared with heavily polluted settings (e.g., India, China, where annual means often exceed 50–100 μg/m³) further constrains the contrast available for estimating concentration–response relationships and may contribute to null or imprecise estimates even when underlying biologic effects exist [@Nagashima2021AirPollutionJapanReview; @Liu2019PM25T2D_Taiwan; @Adar2023PM25GlycemicMarkersIndia]. Studies conducted in high-pollution settings have greater exposure contrast and consequently greater statistical power to detect associations, whereas low-pollution settings such as contemporary Japan may require very large individual-level sample sizes or long follow-up periods to detect modest effect sizes.

An additional limitation is multicollinearity among prefecture-level covariates (e.g., obesity, smoking, exercise, aging), which may inflate standard errors and reduce the precision of partial effect estimates. We therefore report sensitivity analyses and emphasize cautious interpretation of null partial associations for PM2.5. The cross-sectional ecological design precludes causal inference and temporal sequence assessment, and unmeasured confounders (e.g., dietary patterns, genetic susceptibility, occupational exposures) cannot be ruled out. Finally, the NDB Open Data provide only aggregate prescription volume rather than patient-level data, precluding adjustment for disease severity, comorbidities, or treatment adherence, all of which may confound the PM2.5–prescription relationship.

## 7. Implications and Future Directions

Future work should move beyond coarse prefectural averages by incorporating finer geographic units, such as municipalities or secondary medical areas, and by using high-resolution exposure models that integrate satellite-derived aerosol optical depth and land-use information to reduce spatial misalignment [@Anselin1988SpatialEconometrics; @Zeger2000MeasurementError]. Individual-level longitudinal studies linking residential histories, clinical data, and detailed behavioral risk factors would allow more rigorous control of confounding and formal assessment of effect modification by socioeconomic status or comorbidities, building on existing cohort evidence from Asia and other regions [@Liu2019PM25T2D_Taiwan; @Kim2019PM25DiabetesKorea; @Peng2016AirPollutionDiabetesChina; @Yang2018PM25MetabolicSyndrome; @Yamazaki2021PM25DiabetesJapan; @Chen2023PM25ComponentsChina; @Yang2024PM25ChineseWomen].

In parallel, multipollutant and component-specific models focusing on toxicologically relevant PM2.5 constituents (e.g., black carbon, organic matter, secondary aerosols, trace metals) may help clarify whether particular mixtures are more diabetogenic than others and better align epidemiologic contrasts with mechanistic insights from experimental studies [@Rajagopalan2019AirPollutionMetabolic; @Sun2010AirPollutionInsulinResistance; @Wang2025TRPV1Mechanism; @Park2023PM25CircadianDysfunction]. Recent evidence suggests that specific PM2.5 components (e.g., elemental carbon, transition metals, polycyclic aromatic hydrocarbons) may drive diabetogenic effects through distinct pathways, and component-specific exposure assessment could refine risk estimates [@Chen2023PM25ComponentsChina].

Finally, triangulating evidence from ecological analyses, individual-level cohorts, mechanistic experiments, and intervention studies will be essential to fully characterize how ambient air pollution contributes to diabetes risk and to identify the populations most likely to benefit from air quality improvements [@Yang2020AirPollutionDiabetes; @Eze2015AirPollutionDiabetes; @Nagashima2021AirPollutionJapanReview; @Li2019AirPollutionDiabetesReview; @Bowe2019PM25DiabetesCohortVeterans]. Even in low-pollution settings such as contemporary Japan, continued air quality monitoring and health surveillance remain warranted given the well-established biological mechanisms linking particulate air pollution to metabolic dysfunction.

---

# Conclusion

Prefecture-level ambient PM2.5 exposure was not detectably associated with diabetes-related indicators in Japan in this ecological analysis using NDB Open Data. These null findings were robust to sensitivity analyses but require cautious interpretation given exposure assessment limitations, the constraints of ecological inference, and the narrow exposure range in contemporary Japan. The absence of detectable associations at the prefectural level does not preclude biologically meaningful effects at the individual level or in high-pollution settings, and future research using finer geographic resolution and individual-level longitudinal data is warranted.

---
"""

print("Improved Discussion with new citations prepared.")
print("Note: This uses [@...] format. Will need to convert to numbered format.")
print("Total new citations added: 15 (bringing total from 25 to 40)")
